### ISSUE TITLE
How to wirring CC1101 module to display?

### ISSUE THREAD

**Issue by DRCRecoveryData** [GthiN89/NucleusESP32#2]
Hi,

Could you update the pinout connect from CC1101 to CYD ( ILI9341 )?

**Comment by GthiN89** [comment]
its accessible in the source code, in globals.h file, if you cant write your own code, i do not recoment this firmware in this stage of development, bc its barely working now.
anyway...
CC1101_CS   21  // Chip Select
CC1101_MOSI 4   // Master Out Slave In
CC1101_MISO 35  // Master In Slave Out
CC1101_SCLK 22  // Serial Clock

CCGDO0A 17      // GDO0
CCGDO2A 16      // GDO2

you will also need to desolder RGB diod, here is what pin is what on rgb diod, bc those are used to connect CC1101 instead.
Red LED | GPIO 4
Green LED | GPIO 16
Blue LED | GPIO 17

in this stage of development, it can record and play subghz signal back, but can not play it from SD card, where its saved (but im think, that files are saved properly now, i just did not calibrate transmision from files yet... Different code cause different timing issue i suppose)

**Comment by GthiN89** [comment]
sonsider it closed
